### ISSUE TITLE
Update Alibi Explainer Library to 0.4.0

### ISSUE THREAD

**Issue by cliveseldon** [kubeflow/kfserving#792] opened 2020-04-22 06:49 UTC
/kind bug

[Alibi](https://github.com/SeldonIO/alibi) has released 0.4.0 which has some breaking changes. Our current explainer wrapper has a setup.py which isn't fixed to 0.3.0:

https://github.com/kubeflow/kfserving/blob/3b282458eafe7fa423f7f4dcc34bd8f492c07884/python/alibiexplainer/setup.py#L36

We need to:

 * Fix Alibi explainer wrapper to 0.3.0 to keep existing functionality
 * Update and handle breaking changes for 0.4.0

**Comment by irvifa** [comment] 2020-04-30 13:46
Is this indeed a bug?

**Comment by owennewo** [comment] 2020-05-19 18:29
Is this a duplicate of #803

**Comment by cliveseldon** [comment] 2020-05-19 19:29
#803 is the PR for this issue

**Closed** 2020-05-26 11:15 UTC
Labels: kind/bug
