### ISSUE TITLE
OpenAPI spec for V2 Inference does not pass

### ISSUE THREAD

**Issue by awcchungster** [kubeflow/kfserving#1595] opened 2021-05-04 15:29 UTC
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I attempted to run the openapi spec in an AWS API Gateway, but the validation had an error. I reran the same openapi spec through a 3rd party website validator and it also broke.

https://github.com/kubeflow/kfserving/blob/master/docs/predict-api/v2/rest_predict_v2.yaml

**What did you expect to happen:**
Depending on the validator, there are different errors. API gateway returns: The string was placed in a field that did not expect it.

Swagger validator returns:
```
Swagg er schema validation failed. 
  Data does not match any schemas from 'oneOf' at #/components/schemas/tensor_data
    Data does not match any schemas from 'oneOf' at #/components/schemas/tensor_data/items
      Data does not match any schemas from 'oneOf' at #/items/anyOf/1
        Expected type string but found type array at #/anyOf/1/type
        Missing required property: $ref at #/anyOf/1
      Missing required property: $ref at #/items
    Missing required property: $ref at #/components/schemas/tensor_data
 
JSON_OBJECT_VALIDATION_FAILED

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

```

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by cliveseldon** [comment] 2021-05-04 16:11
Thanks @awcchungster

**Comment by yuzisun** [comment] 2021-05-05 00:00
see https://github.com/kubeflow/kfserving/pull/1568

**Comment by yuzisun** [comment] 2021-05-06 21:45
@awcchungster Can you help check if the issue is fixed now?

**Comment by yuzisun** [comment] 2021-05-09 22:35
validated on https://editor.swagger.io/

**Closed by yuzisun** 2021-05-09 22:35 UTC
Labels: kind/bug, v2-protocol
